#!/usr/bin/env python3
"""Build self-contained NXP Cup learning pages from readable source assets."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
LEARN_ROOT = REPO_ROOT / "docs" / "learn"
SOURCE_ROOT = LEARN_ROOT / "src"
THREE_BUNDLE = LEARN_ROOT / "vendor" / "three" / "three.iife.min.js"
CAMERA_THREE_BUNDLE = LEARN_ROOT / "vendor" / "three" / "three-camera.iife.min.js"
OUTPUT = LEARN_ROOT / "color-spaces.html"
RGB565_OUTPUT = LEARN_ROOT / "rgb565-lookup.html"
FRAMEWORK_OUTPUT = LEARN_ROOT / "framework-structure.html"
FRAME_INDEXING_OUTPUT = LEARN_ROOT / "frame-indexing.html"
CAMERA_SCANLINE_LAB_OUTPUT = LEARN_ROOT / "camera_scanline_lab.html"

GENERATED_NOTICE = "<!-- Generated by scripts/tools/build_learning_pages.py. -->"
STYLE_MARKER = "<!-- __LESSON_CSS__ -->"
THREE_MARKER = "<!-- __THREE_JS__ -->"
APP_MARKER = "<!-- __LESSON_JS__ -->"


@dataclass(frozen=True)
class Lesson:
    slug: str
    output: Path
    include_three: bool = False


LESSONS = (
    Lesson("color-spaces", OUTPUT, include_three=True),
    Lesson("rgb565-lookup", RGB565_OUTPUT),
    Lesson("framework-structure", FRAMEWORK_OUTPUT),
    Lesson("frame-indexing", FRAME_INDEXING_OUTPUT, include_three=True),
)


def _read(path: Path) -> str:
    if not path.is_file():
        raise FileNotFoundError(f"required learning-page asset is missing: {path}")
    return path.read_text(encoding="utf-8")


def _safe_inline_script(path: Path) -> str:
    content = _read(path)
    if re.search(r"</script", content, flags=re.IGNORECASE):
        raise ValueError(f"inline script contains a closing script tag: {path}")
    return content


def render_lesson(lesson: Lesson) -> str:
    template = _read(SOURCE_ROOT / f"{lesson.slug}.template.html")
    css = _read(SOURCE_ROOT / "lesson.css")
    lesson_js = _safe_inline_script(SOURCE_ROOT / f"{lesson.slug}.js")

    markers = [STYLE_MARKER, APP_MARKER]
    if lesson.include_three:
        markers.append(THREE_MARKER)
    elif THREE_MARKER in template:
        raise ValueError(f"{lesson.slug} must not include unused Three.js payload")
    for marker in markers:
        if template.count(marker) != 1:
            raise ValueError(f"template must contain exactly one {marker}")

    rendered = template.replace(STYLE_MARKER, f"<style>\n{css}</style>")
    if lesson.include_three:
        three_js = _safe_inline_script(THREE_BUNDLE)
        rendered = rendered.replace(THREE_MARKER, f"<script>\n{three_js}</script>")
    rendered = rendered.replace(APP_MARKER, f"<script>\n{lesson_js}</script>")
    rendered = rendered.replace("<!-- __GENERATED_NOTICE__ -->", GENERATED_NOTICE)

    if "__LESSON_" in rendered or "__THREE_JS__" in rendered:
        raise ValueError("unresolved learning-page marker remains")
    if re.search(r"<(?:script|link)\b[^>]+(?:src|href)\s*=", rendered, re.IGNORECASE):
        raise ValueError("standalone learning page contains an external script or stylesheet")
    return rendered.replace("\r\n", "\n").rstrip() + "\n"


def render_color_spaces() -> str:
    return render_lesson(LESSONS[0])


def render_rgb565_lookup() -> str:
    return render_lesson(LESSONS[1])


def render_framework_structure() -> str:
    return render_lesson(LESSONS[2])


def render_frame_indexing() -> str:
    return render_lesson(LESSONS[3])


def _fragment(source: str, name: str) -> str:
    pattern = rf"<!-- __{name}_BEGIN__ -->(.*?)<!-- __{name}_END__ -->"
    match = re.search(pattern, source, flags=re.DOTALL)
    if match is None:
        raise ValueError(f"camera scanline lab fragment is missing {name}")
    return match.group(1).strip()


def render_camera_scanline_lab() -> str:
    """Extend the preserved simulator without modifying its presentation copy."""
    rendered = _read(LEARN_ROOT / "camera_sim.html")
    fragment_source = _read(SOURCE_ROOT / "camera-scanline-lab.fragment.html")
    lab_css = _read(SOURCE_ROOT / "camera-scanline-lab.css").rstrip()
    lab_js = _safe_inline_script(SOURCE_ROOT / "camera-scanline-lab.js").rstrip()

    replacements = (
        ("<title>NXP Cup — Line-Camera Simulator</title>",
         "<title>NXP Cup — Interactive One-Bit Scanline Lab</title>"),
        ("</style>", f"\n{lab_css}\n</style>"),
        ('  <div id="left">\n    <div id="overview"></div>',
         '  <div id="left">\n' + _fragment(fragment_source, 'TOOLBAR') +
         '\n    <div id="overview"></div>'),
        ('      <h1>Line-Camera Simulator</h1>',
         '      <div class="panel-title-row"><h1>Line-Camera Simulator</h1>' +
         _fragment(fragment_source, "PANEL_LAB_BUTTON") + '</div>'),
        ('      <input id="row1" type="range" min="0" max="199" step="1" value="150">',
         '      <input id="row1" type="range" min="0" max="199" step="1" value="150">\n' +
         _fragment(fragment_source, "SECOND_ROW_CONTROLS") + '\n' +
         _fragment(fragment_source, "MAIN_FILTER_CONTROLS")),
        ('    <h2>Raw scan-row Y profile (luma from RGB565, like the MCU LUT)</h2>\n'
         '    <canvas id="plot1" class="plot" width="640" height="130"></canvas>',
         '    <div id="rawPlotGroup" class="binary-plot-group">\n'
         '      <h2>Raw scan-row Y profile (luma from RGB565, like the MCU LUT)</h2>\n'
         '      <canvas id="plot1" class="plot" width="640" height="96"></canvas>\n'
         '    </div>\n' +
         _fragment(fragment_source, "MAIN_FILTER_PLOT") + '\n' +
         _fragment(fragment_source, "SECOND_PLOT")),
        ('// per-pixel inverse projection of the whole 320x240 frame (CPU, ~77k rays).',
         '// per-pixel inverse projection of the whole 320x200 frame (CPU, 64k rays).'),
        ('      rowBuf[x] = (77 * f.data[p] + 150 * f.data[p+1] + 29 * f.data[p+2]) >> 8;',
         '      rowBuf[x] = (77 * f.data[p] + 150 * f.data[p+1] + 29 * f.data[p+2] + 128) >> 8;'),
        ('Y = (77R+150G+29B)&gt;&gt;8 from RGB565',
         'Y = (77R+150G+29B+128)&gt;&gt;8 from RGB565'),
        ('<script type="importmap">',
         f"{_fragment(fragment_source, 'LAB')}\n\n<script type=\"importmap\">"),
        ('  }\n}\nanimate();\n</script>\n</body>',
         f"    scanlineLabOnFrame(f);\n  }}\n}}\n\n{lab_js}\n\nanimate();\n</script>\n</body>"),
    )
    for old, new in replacements:
        if rendered.count(old) != 1:
            raise ValueError(f"camera simulator source marker changed: {old[:80]!r}")
        rendered = rendered.replace(old, new, 1)

    three_js = _safe_inline_script(CAMERA_THREE_BUNDLE)
    rendered, importmap_count = re.subn(
        r'<script type="importmap">.*?</script>\s*',
        lambda _: f"<script>\n{three_js}\n</script>\n",
        rendered,
        count=1,
        flags=re.DOTALL,
    )
    if importmap_count != 1:
        raise ValueError("camera simulator import map marker changed")
    rendered = rendered.replace('<script type="module">', '<script>', 1)
    for import_line in (
        "import * as THREE from 'three';\n",
        "import { OrbitControls } from 'three/addons/controls/OrbitControls.js';\n",
        "import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';\n",
    ):
        if rendered.count(import_line) != 1:
            raise ValueError(f"camera simulator import changed: {import_line.strip()}")
        rendered = rendered.replace(import_line, "", 1)
    rendered = rendered.replace("new OrbitControls(", "new THREE.OrbitControls(")
    rendered = rendered.replace("new GLTFLoader()", "new THREE.GLTFLoader()")
    rendered = rendered.replace(
        "<!DOCTYPE html>", f"<!DOCTYPE html>\n{GENERATED_NOTICE}", 1
    )
    if re.search(
        r"<(?:script|link)\b[^>]+(?:src|href)\s*=", rendered, re.IGNORECASE
    ) or 'type="importmap"' in rendered:
        raise ValueError("camera scanline lab contains a runtime network dependency")
    return rendered.replace("\r\n", "\n").rstrip() + "\n"


def build(*, check: bool) -> int:
    status = 0
    for lesson in LESSONS:
        expected = render_lesson(lesson)
        current = (
            lesson.output.is_file()
            and lesson.output.read_text(encoding="utf-8") == expected
        )
        if check:
            if not current:
                print(f"stale or missing: {lesson.output}", file=sys.stderr)
                status = 1
            else:
                print(f"Standalone learning page is current: {lesson.output}")
        elif current:
            print(f"Standalone learning page already current: {lesson.output}")
        else:
            lesson.output.write_text(expected, encoding="utf-8", newline="\n")
            print(f"Built standalone learning page: {lesson.output}")
    camera_lab_expected = render_camera_scanline_lab()
    camera_lab_current = (
        CAMERA_SCANLINE_LAB_OUTPUT.is_file()
        and CAMERA_SCANLINE_LAB_OUTPUT.read_text(encoding="utf-8")
        == camera_lab_expected
    )
    if check:
        if not camera_lab_current:
            print(f"stale or missing: {CAMERA_SCANLINE_LAB_OUTPUT}", file=sys.stderr)
            status = 1
        else:
            print(f"Standalone learning page is current: {CAMERA_SCANLINE_LAB_OUTPUT}")
    elif camera_lab_current:
        print(f"Standalone learning page already current: {CAMERA_SCANLINE_LAB_OUTPUT}")
    else:
        CAMERA_SCANLINE_LAB_OUTPUT.write_text(
            camera_lab_expected, encoding="utf-8", newline="\n"
        )
        print(f"Built standalone learning page: {CAMERA_SCANLINE_LAB_OUTPUT}")
    return status


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify the committed output")
    arguments = parser.parse_args(argv)
    return build(check=arguments.check)


if __name__ == "__main__":
    raise SystemExit(main())
